import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background.secondary,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 60,
        paddingHorizontal: 24,
        paddingBottom: 20,
        backgroundColor: theme.colors.background.primary,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        ...theme.shadows.sm,
    },
    backButton: {
        padding: 8,
        marginLeft: -8,
    },
    headerTitle: {
        ...theme.typography.h2,
        fontSize: 20,
    },
    headerButton: {
        padding: 8,
    },
    headerActions: {
        flexDirection: 'row',
        gap: 12,
    },
    tabBar: {
        flexDirection: 'row',
        backgroundColor: theme.colors.background.primary,
        marginHorizontal: 24,
        marginTop: 24,
        borderRadius: theme.borderRadius.round,
        padding: 4,
        ...theme.shadows.sm,
    },
    tab: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderRadius: theme.borderRadius.round,
    },
    activeTab: {
        backgroundColor: theme.colors.primary + '10',
    },
    tabText: {
        ...theme.typography.body,
        fontSize: 14,
        color: theme.colors.text.secondary,
    },
    activeTabText: {
        color: theme.colors.primary,
        fontWeight: '600',
    },
    badge: {
        backgroundColor: theme.colors.primary,
        borderRadius: 12,
        paddingHorizontal: 6,
        paddingVertical: 2,
        marginLeft: 6,
    },
    badgeText: {
        color: '#FFF',
        fontSize: 10,
        fontWeight: '600',
    },
    list: {
        padding: 24,
        paddingTop: 16,
    },
    fileCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.card,
        borderRadius: theme.borderRadius.lg,
        padding: 16,
        marginBottom: 12,
        ...theme.shadows.sm,
    },
    fileCardSelected: {
        backgroundColor: theme.colors.primary + '08',
        borderWidth: 2,
        borderColor: theme.colors.primary,
    },
    fileIcon: {
        width: 48,
        height: 48,
        borderRadius: theme.borderRadius.md,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    fileInfo: {
        flex: 1,
    },
    fileName: {
        ...theme.typography.body,
        fontWeight: '500',
        marginBottom: 4,
    },
    fileMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 2,
    },
    fileSize: {
        ...theme.typography.caption,
        color: theme.colors.text.secondary,
    },
    fileDot: {
        ...theme.typography.caption,
        color: theme.colors.text.muted,
        marginHorizontal: 6,
    },
    fileModified: {
        ...theme.typography.caption,
        color: theme.colors.text.secondary,
    },
    fileDevice: {
        ...theme.typography.caption,
        color: theme.colors.text.muted,
        fontSize: 11,
    },
    checkbox: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: theme.colors.text.muted,
        justifyContent: 'center',
        alignItems: 'center',
    },
    checkboxChecked: {
        backgroundColor: theme.colors.primary,
        borderColor: theme.colors.primary,
    },
    storageHeader: {
        backgroundColor: theme.colors.card,
        borderRadius: theme.borderRadius.lg,
        padding: 16,
        marginBottom: 16,
        ...theme.shadows.sm,
    },
    storageInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    storageText: {
        ...theme.typography.body,
        fontWeight: '500',
        marginLeft: 8,
    },
    storageBar: {
        height: 8,
        backgroundColor: theme.colors.border,
        borderRadius: 4,
        marginBottom: 8,
    },
    storageUsed: {
        height: 8,
        backgroundColor: theme.colors.primary,
        borderRadius: 4,
    },
    storageDetails: {
        ...theme.typography.caption,
        color: theme.colors.text.secondary,
    },
    remoteContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
    },
    remoteTitle: {
        ...theme.typography.h2,
        marginTop: 24,
        marginBottom: 8,
    },
    remoteText: {
        ...theme.typography.body,
        color: theme.colors.text.secondary,
        textAlign: 'center',
        marginBottom: 24,
    },
    connectButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.primary,
        paddingHorizontal: 24,
        paddingVertical: 14,
        borderRadius: theme.borderRadius.round,
        ...theme.shadows.md,
    },
    connectButtonText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
    },
    transferCard: {
        backgroundColor: theme.colors.card,
        borderRadius: theme.borderRadius.lg,
        padding: 16,
        marginBottom: 12,
        ...theme.shadows.sm,
    },
    transferHeader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    transferInfo: {
        flex: 1,
        marginLeft: 12,
    },
    transferName: {
        ...theme.typography.body,
        fontWeight: '500',
        marginBottom: 2,
    },
    transferMeta: {
        ...theme.typography.caption,
        color: theme.colors.text.secondary,
    },
    transferStatus: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: theme.borderRadius.sm,
    },
    transferStatusText: {
        fontSize: 12,
        fontWeight: '600',
        textTransform: 'uppercase',
    },
    progressContainer: {
        marginTop: 12,
        height: 4,
        backgroundColor: theme.colors.border,
        borderRadius: 2,
        position: 'relative',
    },
    progressBar: {
        height: 4,
        backgroundColor: theme.colors.primary,
        borderRadius: 2,
    },
    progressText: {
        position: 'absolute',
        right: 0,
        top: -18,
        fontSize: 10,
        color: theme.colors.text.secondary,
    },
    footer: {
        paddingVertical: 16,
        alignItems: 'center',
    },
    footerText: {
        ...theme.typography.caption,
        color: theme.colors.text.secondary,
    },
    pickButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.colors.primary,
        borderRadius: theme.borderRadius.round,
        paddingVertical: 12,
        marginBottom: 16,
    },
    pickButtonText: {
        color: '#FFF',
        fontWeight: '600',
        marginLeft: 8,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: theme.colors.background.primary,
        borderRadius: theme.borderRadius.lg,
        padding: 24,
        alignItems: 'center',
        width: '80%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: theme.colors.text.primary,
    },
    webUrl: {
        marginTop: 16,
        fontSize: 12,
        color: theme.colors.text.secondary,
        textAlign: 'center',
    },
    copyButton: {
        flexDirection: 'row',
        backgroundColor: theme.colors.primary,
        borderRadius: theme.borderRadius.round,
        paddingVertical: 10,
        paddingHorizontal: 20,
        marginTop: 20,
    },
    copyButtonText: {
        color: '#FFF',
        marginLeft: 8,
    },
});
